### ISSUE TITLE
Error_CheckModeration

### ISSUE THREAD

**Issue by dgoryeo** [Cerlancism/chatgpt-subtitle-translator#44] opened 2024-10-22 13:43 UTC
I tried to use the new feature  `--experimental-use-full-context `  by upgrading the repo and to installl locally. But I get the following error upon execution: 

```
[Translator] System Instruction: Translate zh to en
[Error_CheckModeration] 2024-10-22T20:38:46.040Z Status 500 Error 500 Unexpected error {
  message: 'Unexpected error',
  type: 'server_error',
  param: null,
  code: null
}

```
I wonder if this is caused by a mistake in my repo upgrade or something in the main repo

**Comment by Cerlancism** [comment] 2024-10-22 13:58
Is this the full output? What is what is the full command? Are you able to provide the file?

You also try to turn off moderator
`--no-use-moderator`

**Comment by Cerlancism** [comment] 2024-10-23 14:35
Any follow ups?

**Comment by dgoryeo** [comment] 2024-10-23 14:54
I have reached insufficient quota. I get insufficient quota error. 
Which I guess it means that it works now, right? 
I'll try after I have toped up my credit again. 
Meanwhile, here is the sub I was testing on: 
https://drive.google.com/file/d/1bo-LJ7dmZFzKLuraLipDhN4f4PBn4cAa/view?usp=sharing

**Comment by Cerlancism** [comment] 2024-10-23 15:54
The input file works, ok, so should be issues you need to resolve from the endpoint you are using.
![image](https://github.com/user-attachments/assets/cc0b3af4-b24c-4e8c-a201-65e93236344c)

**Comment by Cerlancism** [comment] 2024-11-23 08:51
Closing to cleanup and error is caused by external server side endpoint.

**Closed by Cerlancism** 2024-11-23 08:51 UTC
Labels: question
